### ISSUE TITLE
Implement play drum block

### ISSUE THREAD

**Issue by ericrosenbaum** [LLK/scratch-audioengine#1]
We'll need a set of 18 drum sounds to match the scratch 2.0 play drum block. We can start with the existing sounds:

https://github.com/LLK/scratch-flash/tree/master/src/soundbank/drums  

And optionally work on replacing them with higher quality sounds.

**Comment by as-com** [comment]
We can probably just ~~steal~~ borrow the drum sounds from FluidR3. They are pretty nice, and the soundfont is public domain.

**Comment by ericrosenbaum** [comment]
As of https://github.com/LLK/scratch-audio/commit/ad81e1d3deb0393275827b268511def7706a6269 we have drum sounds matching those in Scratch 2.0 (I used the same audio files). I'll open a new issue for updating these with improved quality sounds.
