### ISSUE TITLE
Notes initially ignore volume

### ISSUE THREAD

**Issue by Robomandude** [LLK/scratch-audioengine#102]
### Expected behavior

Notes (from the music extension) should play at the specified volume from beginning to end.

### Actual behavior

Notes ignore volume for a brief period of time before playing at the correct volume

### Steps to reproduce

Set volume to 0%(or any value less than 100)
Play a note

### Operating system and browser

Windows 7, Chrome Version 68.0.3440.106 (Official Build) (64-bit)

**Comment by ericrosenbaum** [comment]
Moving this to the VM (https://github.com/LLK/scratch-vm/issues/1732)
