### ISSUE TITLE
The instruments could use some tweaks

### ISSUE THREAD

**Issue by Robomandude** [LLK/scratch-audioengine#108]
### Expected behavior

All the instruments in Scratch 3 should sound _similar_ to their Scratch 2 counterparts, if not identical.
None of the instruments should be substantially louder or softer than the other instruments.

### Actual behavior

Some of the instruments are very quiet compared to the others in Scratch 3.  Some examples include the ludicrously quiet electric guitar, and the unusually quiet saxophone.  This makes them nearly inaudible when paired with other sounds that easily drown them out.
These are not the only examples; all of the instruments vary wildly in volume.

A few instruments sound dramatically different in Scratch 3 than they did in Scratch 2.
The biggest offenders are the Synth instruments
Synth Lead is a sawtooth wave in Scratch 2 and is a square wave in Scratch 3
Synth Pad is a complicated, soft wave in Scratch 2 and a slightly distorted and loud sine wave in Scratch 3
Here is a comparison of the waveforms captured in Audacity (volume boosted for visibility)
![scratch2-3 synth waveform comparison](https://user-images.githubusercontent.com/14086052/48029913-15bbeb80-e115-11e8-9ca9-96f9cb4deda5.png)

While they may still be accurate to their _name_, they sound very different than they did before, and any project using these instruments will sound different.

In addition the music box sounded more like a glockenspiel in Scratch 2 and sounds like a cheap music box in Scratch 3. 

### Steps to reproduce
Use various instruments in a Scratch project.

https://llk.github.io/scratch-gui/develop/compatibility-testing.html#183652049

### Operating system and browser

N/A

**Comment by ericrosenbaum** [comment]
Thanks! I'm going to move this to the VM repo (that's where the fixes are needed): https://github.com/LLK/scratch-vm/issues/1734
