### ISSUE TITLE
Set volume to in a forever loop causes audio to stutter on Firefox

### ISSUE THREAD

**Issue by BryceLTaylor** [LLK/scratch-audioengine#116]
### Expected behavior

If there is a "set volume to [ ] %" block inside a forever loop the audio should play back smoothly.

### Actual behavior

On Firefox, if the volume is set to any number other than 100, the audio plays and stutters.  It even plays sound if you set the number to 0.

### Steps to reproduce

Create a new project
Add a sound to the cat such as "eggs"
Build this stack:
![screen shot 2019-01-11 at 1 53 42 pm](https://user-images.githubusercontent.com/1088291/51053688-5407d800-15a8-11e9-90bd-15d01eb68d3e.png)
Create a variable called "volume"
Create this stack:
![screen shot 2019-01-11 at 1 50 21 pm](https://user-images.githubusercontent.com/1088291/51053537-ec518d00-15a7-11e9-9d5a-184fa50fc408.png)
Change the monitor for the variable "volume" to a slider
Click the green flag
Note: since the variable "volume" is at 0 it should not make any sound.  Instead it plays the sound "eggs" with a sort of stutter.
Drag the slider up to 100
Note: at 100 the stutter can not be heard.
Set the slider to 50 or so
Note: the stutter is back but the quite parts still play the sound some

I have created this project that has that code: https://scratch.mit.edu/projects/278900980/
This was originally brought to our attention through the forums with this project: https://scratch.mit.edu/projects/214860997/

### Operating system and browser

Windows Firefox
Mac Firefox
No other browsers

**Comment by towerofnix** [comment]
Related to or perhaps the same issue as #111, BTW.
