### ISSUE TITLE
Extend the pitch effects limit

### ISSUE THREAD

**Issue by Kouzeru** [LLK/scratch-audioengine#129]
It's great having dynamic playback of sounds, especially having realtime volume controls and pitch effects.

I had wrote [a synthesizer](https://turbowarp.org/471351085?fps=60) which utilizes the effects while playing the samples. However, having the pitch limit -360 to 360 seem not quite enough to manipulate the playback of a single sample, and it's also hard to alternate between two samples which has different octaves since there is no way to stop specific sound.

Having A-3 as the base note, with limit -360 and 360 will make it only go from A-0 to A-6, which is insufficient having full notes such as C-0 and B-7. I propose to extend the pitch limit instead from -360 to 360, it will go from -480 to 480, that'd be nice four octaves relative.

**Comment by Kouzeru** [comment]
@ericrosenbaum 

I don't think this is quite noticeable but, I hope there would be some consideration upon this. 😄

**Comment by ericrosenbaum** [comment]
Hi @Kouzeru thanks for your interest and ideas! Your synthesizer project is impressive. 

Generally speaking, we avoid making changes to the behavior of blocks. Extending the range of the pitch effect could cause unexpected changes to existing projects that rely on the current behavior.

**Comment by Kouzeru** [comment]
> Hi @Kouzeru thanks for your interest and ideas! Your synthesizer project is impressive.
> 
> Generally speaking, we avoid making changes to the behavior of blocks. Extending the range of the pitch effect could cause unexpected changes to existing projects that rely on the current behavior.

Thanks for the response about that @ericrosenbaum - though I wanted them much simpler to develop.
Maybe, for the solution, I'd prefer to assign the effect parameter with something like:

![image](https://user-images.githubusercontent.com/46141631/105454465-de699300-5cbc-11eb-9119-4dfaab3498db.png)


Just like how Scratch handle hexadecimals as number

![image](https://user-images.githubusercontent.com/46141631/105454485-e88b9180-5cbc-11eb-8dc4-a9c494749012.png)

While preserving the behavior that the projects relied upon the pitch limits.
Please, provide a way to bypass it.
