### ISSUE TITLE
module is not defined

### ISSUE THREAD

**Issue by jasonglenevans** [LLK/scratch-audioengine#178]
### Expected Behavior

it will work with no errors and i can attach it with the scratch vm.

### Actual Behavior

throws an error: module is not defined when loading in my html page.

### Steps to Reproduce

_Explain what someone needs to do in order to see what's described in *Actual behavior* above_

`
yarn add scratch-audio
cd node_modules\scratch-audio
yarn install
yarn build
`
then i copy dist.js ovet to my html program and add it in the scripts

### System Details
5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.51 Safari/537.36

**Comment by ericrosenbaum** [comment]
It's hard to help without knowing a bit more- can you explain what you're trying to do and why? (it might be helpful to look at the instructions in the scratch-gui [repo](https://github.com/LLK/scratch-gui))
