### ISSUE TITLE
"Play sound until done" does not highlight while playing

### ISSUE THREAD

**Issue by ericrosenbaum** [LLK/scratch-audioengine#19]
### Expected behavior

When you click a "play sound until done" block, it should highlight during the duration of the sound. 

The block does have the correct timing behavior, waiting until the sound completes to continue to execution of the next block in the stack (so, for example, this stack highlights correctly: repeat 10 [play sound and wait]).

### Actual behavior

No highlight appears.

### Steps to reproduce

Drag out a "play sound until done" block and click on it

### Operating system and browser

Mac OS 10.11.6 Chrome 56.0.2924.87

**Comment by ericrosenbaum** [comment]
I suspect that I am incorrectly returning the Promise that resolves when the sound has ended, which is here:

https://github.com/LLK/scratch-audio/blob/5007c43ddfdd45ca3294ad4659cbaae8c2d3bfa9/src/SoundPlayer.js#L71-L84

For a comparison, the play note, play drum, and rest blocks all use this function, which results in the correct highlight behavior:

https://github.com/LLK/scratch-audio/blob/5007c43ddfdd45ca3294ad4659cbaae8c2d3bfa9/src/index.js#L274-L286

@cwillisf might be able to help?

**Comment by paulkaplan** [comment]
I think the promise stuff is fine actually. This has something to do with the logic behind when to activate the glows. I think it is closely related to this issue, and the fix will probably address both. https://github.com/LLK/scratch-vm/issues/786

**Comment by thisandagain** [comment]
Tracking in https://github.com/llk/scratch-vm/issues/993
