### ISSUE TITLE
Play sound block menu should contain sound names

### ISSUE THREAD

**Issue by ericrosenbaum** [LLK/scratch-audioengine#25]
### Expected behavior

The play sound block has a menu that should list the names of the sounds in the sprite.

### Actual behavior

The menu contains a list of numbers 1 to 10.

### Steps to reproduce

Click on the menu on the play sound block.

### Operating system and browser

Mac OS 10.11.6 Chrome 56.0.2924.87

**Comment by ericrosenbaum** [comment]
The real fix will eventually require work in scratch-blocks and scratch-vm. We may be able to hack in a fix in the meantime using the strategy I used here:

https://github.com/LLK/scratch-ios/blob/6325f0b62c44579d2c41f4614677d72e0a474f12/src/js/common.js#L188-L217

**Comment by TheBrokenRail** [comment]
scratch-ios? I'm guessing this is a IOS port of Scratch 3.0, when will it become public?


________________________________

**Comment by ericrosenbaum** [comment]
Sorry, that was just a prototype. We don't have a schedule for when Scratch 3.0 will be available on iOS and Android yet.

**Comment by TheBrokenRail** [comment]
I guess this is fixed?

**Comment by ericrosenbaum** [comment]
Fixed in https://github.com/LLK/scratch-gui/pull/77
