### ISSUE TITLE
Audio quality will degrade over time until it eventually fails

### ISSUE THREAD

**Issue by thisandagain** [LLK/scratch-audioengine#27]
### Expected behavior

- Should be able to play a long project with audio

### Actual behavior

- Audio quality begins to degrade until eventually it "cuts out" and will not resume audio playback until refreshing the page

### Steps to reproduce

- Load project https://llk.github.io/scratch-gui/#100736613
- Press green flag
- Sit through the entire animation 🐱 
- Press green flag again

### Operating system and browser

Mac OS 10.12.2 Chrome Version 56.0.2924.87 (64-bit)

**Comment by ed-cooper** [comment]
I didn't see anything out of the ordinary when running the project

Windows 10, Chrome 56.0.2924.87 (64-bit)

**Comment by ed-cooper** [comment]
Actually, I do see what @thisandagain describes, although I can't consistently reproduce it.

However, I only experience any issues if I switch to another tab whilst the project is playing.

So maybe this is a fundamental issue to do with how Chrome handles tabs running in the background?

**Comment by towerofnix** [comment]
I'm also able to reproduce this, and, as @chooper100 said, only from switching between tabs.

**Comment by SillyInventor** [comment]
I am able to reproduce this by playing it 3 times in a row. I got degradation by running the program without sound a few times, and then adding in sound. As such I suspect an indirect source. A brief look at the memory usage shows a ~50mb leak every run with or without sound, but more concerning an increasing CPU usage.
![image](https://cloud.githubusercontent.com/assets/8440451/23035423/080df354-f44d-11e6-9127-0cf25d43e024.png)

Using Ubuntu 16.04, Chrome 56.0.2924.87

**Comment by thisandagain** [comment]
An event emitter leak would be my first guess, but we'll need to instrument the audio engine to track that down.

**Comment by SillyInventor** [comment]
Well, after checking the heap, I found there were a lot of gain nodes etc. owned by clones. By eliminating the forever clone loop in sprites 16 and 10 the problem was solved. This may be a result of poor clone disposal.

**Comment by SillyInventor** [comment]
It appears that there is a limit on clones for scratch 2.0 which prevents this.
