### ISSUE TITLE
Freezes With Error In Player Start

### ISSUE THREAD

**Issue by SillyInventor** [LLK/scratch-audioengine#28]
### Expected behavior

Pressing mode button in https://llk.github.io/scratch-gui/#141331752/ should play a brief sound and switch mode.

### Actual behavior

Freezes with warning:
![image](https://cloud.githubusercontent.com/assets/8440451/23235339/28a3fdcc-f923-11e6-8770-ba8c094de04f.png)

### Steps to reproduce

Open https://llk.github.io/scratch-gui/#141331752/ , press green flag, press mode (may have to press for a while to trigger toggle mode).

### Operating system and browser

Ubuntu 16.04, chrome 56.0.2924.87

**Comment by thisandagain** [comment]
@ericrosenbaum can you confirm that your clamping fix has resolved this?

**Comment by ericrosenbaum** [comment]
The fix that clamps the input to the play note block, [here](https://github.com/LLK/scratch-vm/commit/1ba7ad0218474547aded1668f06b9a29559a0364), prevents the reported problem. This particular project is now broken in other ways- I'll open another issue for it in the vm.
