### ISSUE TITLE
IE - Web Audio is not supported

### ISSUE THREAD

**Issue by TheBrokenRail** [LLK/scratch-audioengine#29]
### Expected behavior

_It works without error._

### Actual behavior

_It prevents scratch from loading and throws an error._

### Steps to reproduce

_Try to load Scratch-VM/GUI playground in IE_

### Operating system and browser

_Windows 10 IE_

### Screenshot

![console](https://cloud.githubusercontent.com/assets/17478432/23593842/229273b0-01e2-11e7-8c22-54b840e36f62.PNG)

**Comment by apple502j** [comment]
But according to Preview-FAQ IE won't be supported.

**Comment by thisandagain** [comment]
We will not be supporting Internet Explorer for Scratch 3.0.
