### ISSUE TITLE
LoadSounds should give a callback when the sound is ready to play

### ISSUE THREAD

**Issue by paulkaplan** [LLK/scratch-audioengine#30]
See https://github.com/LLK/scratch-gui/pull/257

Even if we use scratch-storage for the actual loading, there will still need to be something to indicate that the sounds are decoded and ready for playing.

**Comment by ericrosenbaum** [comment]
Fixed in https://github.com/LLK/scratch-audio/commit/cc454f2f725e6f4f4c796505b70e5a4fcd10d118
