### ISSUE TITLE
Running "move _ steps" followed by "play sound _ until done" never completes

### ISSUE THREAD

**Issue by rschamp** [LLK/scratch-audioengine#38]
### Expected behavior

_Please describe what should happen_
The stack should un-highlight after running

### Actual behavior

_Describe what actually happens_
The stack stays highlighted after the sound has completed

### Steps to reproduce

_Explain what someone needs to do in order to see what's described in *Actual behavior* above_
At https://llk.github.io/scratch-gui/ drag out a "move 10 steps" and attach "play sound meow until done" to it.
Run the stack
The cat moves 10 steps and "meow" plays, however the stack remains highlighted after playing

### Operating system and browser

Chrome 57, macOS 10.12

**Comment by ericrosenbaum** [comment]
It looks like this was caused by our updating to Tone js version 9, which has a new wrapper for the onended callback of bufferSource that doesn't have the behavior we expect. I should be able to use the native audioBufferSourceNode instead.
