### ISSUE TITLE
Clones shouldn't have their own AudioPlayers?

### ISSUE THREAD

**Issue by ericrosenbaum** [LLK/scratch-audioengine#51]
Generally, when you run the "play sound" block multiple times with the same sound selected, it stops and restarts the sound. For example this stack plays a stuttering sound, restarting the sound many times per second, rather than playing many overlapping copies of the sound: 

<img width="179" alt="screen shot 2017-06-27 at 2 51 14 pm" src="https://user-images.githubusercontent.com/567844/27604715-20db6eb8-5b48-11e7-87e8-48418f5a0545.png">

In Scratch 2.0, clones of a sprite share their sounds as if they were all being played by the parent sprite, so that if one clone starts  a sound, and another clone then starts it, the sound restarts. So this stack also creates a stuttering sound:

<img width="175" alt="screen shot 2017-06-27 at 3 01 20 pm" src="https://user-images.githubusercontent.com/567844/27605100-96ab10c0-5b49-11e7-98b6-a514f2bcfbb7.png">

In the current implementation for 3.0, each clone gets its own audioPlayer, so many clones can all play the same sound without restarting each other. But this probably creates performance and memory issues (I think this is the cause of https://github.com/LLK/scratch-audio/issues/27, for example).

So probably we should change it so that clones don't have a full audioPlayer. Instead, each sprite has an audioPlayer, and clones would only get a reference to it. 

If we do that, how do we handle the audio effects? 

Generally, how would we implement this?

**Comment by mrjacobbloom** [comment]
Note that that doesn't apply to instruments, only recorded sounds. So the following code will produce a cacophony in 2.0:

<img width="316" alt="screen shot 2017-06-27 at 3 42 48 pm" src="https://user-images.githubusercontent.com/2879020/27611437-6b2ca3b8-5b4f-11e7-8627-22c0847bf97a.png">
