### ISSUE TITLE
Deprecation warning - January 2018

### ISSUE THREAD

**Issue by paulkaplan** [LLK/scratch-audioengine#68]
Just started getting this deprecation warning

```
[Deprecation] GainNode.gain.value setter smoothing is deprecated and will be removed in M64, around January 2018. Please use setTargetAtTime() instead if smoothing is needed. See https://www.chromestatus.com/features/5287995770929152 for more details.
```

@ericrosenbaum can you determine if we want the instantaneous behavior (in which case I guess we keep the setter the way it is) or if we want a smoothed behavior (in which case we should switch to using setTargetAtTime)? 

I'm adding this to the December milestone just to stay ahead of it, but I do not think (judging from the warning) that it would cause any buggy behavior if we let it be. But I'd like to get a decision on the books this month just so we know where we stand.

**Comment by ericrosenbaum** [comment]
We’re using gain.value to set the volume and in the pan effect. Using that setTargetAtTime approach will help make sure those sound good and not clicky. Also we can use it in other places to prevent clicks (as in https://github.com/LLK/scratch-audio/issues/42)
