### ISSUE TITLE
Green Flag and Stop should not reset volume

### ISSUE THREAD

**Issue by ericrosenbaum** [LLK/scratch-audioengine#75]
### Expected behavior

To match the behavior of Scratch 2.0, the green flag and stop button should not reset the volume for a target.

### Actual behavior

Green flag and stop button currently do reset the volume.

### Steps to reproduce

The issue is described with repro here: https://github.com/LLK/scratch-vm/issues/927

It should be as simple as removing this line:
https://github.com/LLK/scratch-audio/blob/84fdf5c76a41a4960e34282ea96687d9ef19d6aa/src/index.js#L125

**Comment by mzgoddard** [comment]
I think this is a VM issue. The VM is creating AudioPlayer objects but not setting the volume of those AudioPlayer's by the volume the RenderedTarget is set to. So the AudioPlayer's are using the default 100 volume.

**Comment by kchadha** [comment]
Seem to be no longer be an issue.
